on: [push]

jobs:
  postgrest:
    runs-on: ubuntu-latest
    name: Build pgformatter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./pgformatter/
        id: build
      - name: Release ID
        id: releases
        run: |
          echo "::set-output name=id::$(curl -s https://api.github.com/repos/nathancahill/lambda-binaries/releases/tags/pgformatter | jq .id)"
      - name: Asset ID
        id: assets
        run: |
          echo "::set-output name=id::$(curl -s https://api.github.com/repos/nathancahill/lambda-binaries/releases/tags/pgformatter | jq .assets[0].id)"
      - name: Clear Asset
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE https://api.github.com/repos/nathancahill/lambda-binaries/releases/assets/${{ steps.assets.outputs.id }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/nathancahill/lambda-binaries/releases/${{ steps.releases.outputs.id }}/assets{?name,label}
          asset_path: ${{ steps.build.outputs.tarball }}
          asset_name: pgformatter.tar.gz
          asset_content_type: application/gzip
